In [3]:
#import needed libraries
import numpy as np



In [4]:
one_dimensional_array = np.array([1, 2, 3])
print(one_dimensional_array)

[1 2 3]


In [6]:
# Create an array with 3 integers, starting from the default integer 0.
b = np.arange(3)
print(b)

[0 1 2]


In [8]:
# Create an array that start from 1 to 20 and incremented by 3
print(np.arange(1, 20,3))

[ 1  4  7 10 13 16 19]


What if you wanted to create an array with five evenly spaced values in the interval from 0 to 100? As you may notice, you have 3 parameters that a function must take. One paremeter is the starting number, in this case 0, the final number 100 and the number of elements in the array, in this case, 5. NumPy has a function that allows you to do specifically this by using np.linspace().

In [9]:
print(np.linspace(0, 100, 5))

[  0.  25.  50.  75. 100.]


In [10]:
# adding specific data type

print(np.linspace(0, 100, 5, dtype=int))



[  0  25  50  75 100]


In [13]:
# trying float data type
c_int = np.arange(1, 20, 3, dtype=float)
print(c_int)

[ 1.  4.  7. 10. 13. 16. 19.]


In [14]:
# let's use a char and see how many characters it can hold

char_arr = np.array(['Welcome to Math for ML!'])
print(char_arr)
print(char_arr.dtype) # Prints the data type of the array

['Welcome to Math for ML!']
<U23


# More on NumPy arrays

1. np.ones() - Returns a new array setting values to one.
2. np.zeros() - Returns a new array setting values to zero.
3. np.empty() - Returns a new uninitialized array.
4. np.random.rand() - Returns a new array with values chosen at random.

In [15]:
# Return a new array of shape 3, filled with ones. 
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [16]:
# Return a new array of shape 3, filled with zeroes.
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [17]:
# Return a new array of shape 3, without initializing entries.
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [25]:
# Return a new array of shape 3 with random numbers between 0 and 1.
rand_arr = np.random.rand(5)
print(rand_arr)

[0.17067255 0.3659747  0.44077629 0.70994011 0.72144817]


# Multidimentional Arrays


In [26]:
print(np.array([[1, 2, 3], [4, 5, 6]])) # 2D array

[[1 2 3]
 [4 5 6]]


In [29]:
# 1-D array 
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

# Multidimensional array using reshape()
multi_dim_arr = np.reshape(
                one_dim_arr, # the array to be reshaped
               (2,3) # dimensions of the new array
              )
# Print the new 2-D array with two rows and three columns
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


#### Finding size, shape and dimension of an array
- ndarray.ndim - Stores the number dimensions of the array.
- ndarray.shape - Stores the shape of the array. Each number in the tuple denotes the lengths of each corresponding dimension.
- ndarray.size - Stores the number of elements in the array.

In [30]:
# Dimension of the 2-D array multi_dim_arr
multi_dim_arr.ndim

2

In [31]:
# Shape of the 2-D array multi_dim_arr
# Returns shape of 2 rows and 3 columns
multi_dim_arr.shape

(2, 3)

In [32]:
# Size of the array multi_dim_arr
# Returns total number of elements
multi_dim_arr.size


6

#### 3 Array math operations


In [33]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays elementwise
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


#### Multiplying vector with a scalar (broadcasting)

In [38]:
vector = np.array([1,2])
print(vector * 1.6)

[1.6 3.2]


### Indexing and slicing

In [40]:
#selecting the third element in the array.
a = ([1, 2, 3, 4, 5])

print(a[2]) # prints 3
# select the first element in the array
print(a[0]) # prints 1

3
1


In [41]:
# Indexing on a 2-D array
two_dim = np.array(([1, 2, 3],
          [4, 5, 6], 
          [7, 8, 9]))

# Select element number 8 from the 2-D array using indices i, j.
print(two_dim[2][1])

8


##### Slicing 

In [43]:
a = ([1, 2, 3, 4, 5])


# Slice the array a to get the array [2,3,4]
sliced_arr = a[1:4]
print(sliced_arr)


[2, 3, 4]


In [44]:
# Slice the array a to get the array [1,2,3]
sliced_arr = a[:3]
print(sliced_arr)

[1, 2, 3]


In [45]:
# Slice the array a to get the array [3,4,5]
sliced_arr = a[2:]
print(sliced_arr)

[3, 4, 5]


In [50]:
# Slice the array a to get the array [1,3,5]
sliced_arr = a[::3]
print(sliced_arr)

sliced_arr = a[::2]
print(sliced_arr)

[1, 4]
[1, 3, 5]


In [51]:
# Note that a == a[:] == a[::]
print(a == a[:] == a[::])

True


In [52]:
# Indexing on a 2-D array
two_dim = np.array(([1, 2, 3],
          [4, 5, 6], 
          [7, 8, 9]))


# Slice the two_dim array to get the first two rows
sliced_arr_1 = two_dim[0:2]
sliced_arr_1



array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
# Similarily, slice the two_dim array to get the last two rows
sliced_two_dim_rows = two_dim[1:3]
print(sliced_two_dim_rows)

[[4 5 6]
 [7 8 9]]


In [59]:
sliced_two_dim_cols = two_dim[1:2,2:3]
print(sliced_two_dim_cols)

[[6]]


In [60]:
sliced_two_dim_cols = two_dim[:,1]
print(sliced_two_dim_cols)

[2 5 8]


##### Stacking

- np.vstack() - stacks vertically
- np.hstack() - stacks horizontally
- np.hsplit() - splits an array into several smaller arrays

In [61]:
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [62]:
# Stack the arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [63]:
# Stack the arrays horizontally
horz_stack = np.hstack((a1, a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]
