In [1]:
import numpy as np

<img src="/Users/eimon/Desktop/Code/My learning/Linear-Algebra-for-Machine-Learning-and-Data-science/Course1_Linear Equation_eElimination_Row_Echelon/pic/1.png" alt="alt text" width="1500"/>

In [7]:
A = np.array([
    [4,-3,1],
    [2,1,3],
    [-1,2,-5]
    ], dtype=np.dtype(float))
B = np.array([-10,0,17],dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nVector B:")
print(B)

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Vector B:
[-10.   0.  17.]


In [10]:
## Let's check the dimensions of A ans B using shape() function

print(f"Shape of A: {np.shape(A)}")
print(f"Shape of B: {np.shape(B)}")

Shape of A: (3, 3)
Shape of B: (3,)


In [11]:
x = np.linalg.solve(A,B)
print(f"Solution of the system: {x}")

Solution of the system: [ 1.  4. -2.]


##### 1.3 - Evaluating the Determinant of a Matrix
Matrix A
 corresponding to the linear system (1)
 is a square matrix - it has the same number of rows and columns. In the case of a square matrix it is possible to calculate its determinant - a real number that characterizes some properties of the matrix. A linear system containing three equations with three unknown variables will have one solution if and only if the matrix 
 has a non-zero determinant.

Let's calculate the determinant using np.linalg.det(A) function:

In [13]:
d = np.linalg.det(A)
print(f"Determinant of A: {d:.2f}")

Determinant of A: -60.00


#### 2- Solving system of Linear Equations using Row Reduction
##### 2.1 - Preparation for Row Reduction
The row reduction method for the linear system with three variables. To apply it, first, unify matrix 
 and array 
 into one matrix using np.hstack() function. Note that the shape of the originally defined array b 
 was (3,)
, to stack it with the (3,3)
 matrix you need to transform it so that it has the same number of dimensions. You can use .reshape((3, 1)) function:

In [23]:
A_System = np.hstack((A,B.reshape((3,1))))
print(A_System)

[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]


#### 2.2 - Function for Elementary Operations

In [24]:
# exchange row_num of the matrix M with its multiple by row_num_multiple

def MultiplyRow(M, row_num, row_num_multiple):
    M_new = M.copy()
    # M_new = M # if you want to change the original matrix
    M_new[row_num]= M_new[row_num]*row_num_multiple
    return M_new

print("Original matrix:")
print(A_System)
print("\nAfter multiplying row 2 by 2:")
print(MultiplyRow(A_System,1,2))

print(f"\n {A_System}")


Original matrix:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

After multiplying row 2 by 2:
[[  4.  -3.   1. -10.]
 [  4.   2.   6.   0.]
 [ -1.   2.  -5.  17.]]

 [[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]


In [25]:
# multiply row_num_1 by row_num_1_multiple and add it to the row_num_2, 
# exchanging row_num_2 of the matrix M in the result
def AddRows(M, row_num_1, row_num_2, row_num_1_multiple):
    M_new = M.copy()
    M_new[row_num_2] = row_num_1_multiple * M_new[row_num_1] + M_new[row_num_2]
    return M_new

print("Original matrix:")
print(A_System)
print("\nMatrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:")
print(AddRows(A_System,1,2,1/2))

Original matrix:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:
[[  4.   -3.    1.  -10. ]
 [  2.    1.    3.    0. ]
 [  0.    2.5  -3.5  17. ]]


In [26]:
# in matrix row 0(index) meands the first row

def SwapRows(M,row_num_1, row_num_2):
    M_new = M.copy()
    M_new[[row_num_1,row_num_2]] = M_new[[row_num_2,row_num_1]]
    return M_new

print("Original matrix:")
print(A_System)
print("\nMatrix after exchange of the first and third rows:")
print(SwapRows(A_System,0,2))

Original matrix:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after exchange of the first and third rows:
[[ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]
 [  4.  -3.   1. -10.]]


##### 2.3 Row reduction and solution of the linear system

In [33]:
A_ref = SwapRows(A_System,0,2)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]
 [  4.  -3.   1. -10.]]


In [34]:
# Multiply row 0 of the new matrix A_ref by 2 and add it to row 1.

A_ref = AddRows(A_ref,0,1,2)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  4.  -3.   1. -10.]]


In [35]:
# multiply row 0 of the new matrix A_ref by 4 and add it to the row 2
A_ref = AddRows(A_ref,0,2,4)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  0.   5. -19.  58.]]


In [36]:
# multiply row 1 of the new matrix A_ref by -1 and add it to the row 2
A_ref = AddRows(A_ref,1,2,-1)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  0.   0. -12.  24.]]


In [37]:
# multiply row 2 of the new matrix A_ref by -1/12
A_ref = MultiplyRow(A_ref,2,-1/12)
print(A_ref)

[[-1.  2. -5. 17.]
 [ 0.  5. -7. 34.]
 [-0. -0.  1. -2.]]


In [54]:
x_3 = -2
x_2 = (A_ref[1,3] - A_ref[1,2] * x_3) / A_ref[1,1]
x_1 = (A_ref[0,3] - A_ref[0,2] * x_3 - A_ref[0,1] * x_2) / A_ref[0,0]

print(x_1, x_2, x_3)

1.0 4.0 -2


##### 3 - System of Linear Equations with No Solutions


In [55]:
A_2 = np.array([
    [1,1,1],
    [0,1,-3],
    [2,1,5]
    ], dtype=np.dtype(float))

b_2 = np.array([2,1,0],dtype=np.dtype(float))
d_2 = np.linalg.det(A_2)
print(f"Determinant of A_2: {d_2:.2f}")

Determinant of A_2: 0.00


In [57]:
#print( np.linalg.solve(A_2,b_2) ) ## it's a singular matrix

In [58]:
A_2_system = np.hstack((A_2, b_2.reshape((3, 1))))
print(A_2_system)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 2.  1.  5.  0.]]


In [59]:
# multiply row 0 by -2 and add it to the row 1
A_2_ref = AddRows(A_2_system,0,2,-2)
print(A_2_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0. -1.  3. -4.]]


In [61]:
# add row 1 of the new matrix A_2_ref to the row 2
A_2_ref = AddRows(A_2_ref,1,2,1)
print(A_2_ref)
print(" The last row shows to the equation 0 = -3 which is impossible, so the system has no solutions.")

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0.  1. -3. -2.]]
 The last row shows to the equation 0 = -3 which is impossible, so the system has no solutions.


##### 4 - System of Linear Equations with Infinite Number of Solutions


In [62]:
b_3 = np.array([2,1,3],dtype=np.dtype(float))

In [63]:
A_3 = A_2 


In [64]:
A_3 = np.hstack((A_3, b_3.reshape((3, 1))))

array([[ 1.,  1.,  1.,  2.],
       [ 0.,  1., -3.,  1.],
       [ 2.,  1.,  5.,  3.]])

In [67]:
# multiply row 0 of the new matrix A_3_system by -2 and add it to the row 2
A_3_ref = AddRows(A_3,0,2,-2)
print(A_3_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0. -1.  3. -1.]]


In [70]:
# add row 1 of the new matrix A_3_ref to the row 2
A_3_ref = AddRows(A_3_ref,1,2,1)
print(A_3_ref)
print (" where last row 0 = 0, i can see x_2 = 1+ 3x_3, and x_1 = 1 - 4 x_3") 

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0.  1. -3.  1.]]
 where last row 0 = 0, i can see x_2 = 1+ 3x_3, and x_1 = 1 - 4 x_3
