In [1]:
import numpy as np

<img src="/Users/eimon/Desktop/Code/My learning/Linear-Algebra-for-Machine-Learning-and-Data-science/Course1_Linear Equation_eElimination_Row_Echelon/pic/1.png" alt="alt text" width="1500"/>

In [7]:
A = np.array([
    [4,-3,1],
    [2,1,3],
    [-1,2,-5]
    ], dtype=np.dtype(float))
B = np.array([-10,0,17],dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nVector B:")
print(B)

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Vector B:
[-10.   0.  17.]


In [10]:
## Let's check the dimensions of A ans B using shape() function

print(f"Shape of A: {np.shape(A)}")
print(f"Shape of B: {np.shape(B)}")

Shape of A: (3, 3)
Shape of B: (3,)


In [11]:
x = np.linalg.solve(A,B)
print(f"Solution of the system: {x}")

Solution of the system: [ 1.  4. -2.]
