In [1]:
import numpy as np

<img src="/Users/eimon/Desktop/Code/My learning/Linear-Algebra-for-Machine-Learning-and-Data-science/Course1_Linear Equation_eElimination_Row_Echelon/pic/1.png" alt="alt text" width="1500"/>

In [7]:
A = np.array([
    [4,-3,1],
    [2,1,3],
    [-1,2,-5]
    ], dtype=np.dtype(float))
B = np.array([-10,0,17],dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nVector B:")
print(B)

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Vector B:
[-10.   0.  17.]


In [10]:
## Let's check the dimensions of A ans B using shape() function

print(f"Shape of A: {np.shape(A)}")
print(f"Shape of B: {np.shape(B)}")

Shape of A: (3, 3)
Shape of B: (3,)


In [11]:
x = np.linalg.solve(A,B)
print(f"Solution of the system: {x}")

Solution of the system: [ 1.  4. -2.]


##### 1.3 - Evaluating the Determinant of a Matrix
Matrix A
 corresponding to the linear system (1)
 is a square matrix - it has the same number of rows and columns. In the case of a square matrix it is possible to calculate its determinant - a real number that characterizes some properties of the matrix. A linear system containing three equations with three unknown variables will have one solution if and only if the matrix 
 has a non-zero determinant.

Let's calculate the determinant using np.linalg.det(A) function:

In [13]:
d = np.linalg.det(A)
print(f"Determinant of A: {d:.2f}")

Determinant of A: -60.00


#### 2- Solving system of Linear Equations using Row Reduction
##### 2.1 - Preparation for Row Reduction
The row reduction method for the linear system with three variables. To apply it, first, unify matrix 
 and array 
 into one matrix using np.hstack() function. Note that the shape of the originally defined array b 
 was (3,)
, to stack it with the (3,3)
 matrix you need to transform it so that it has the same number of dimensions. You can use .reshape((3, 1)) function:

In [23]:
A_System = np.hstack((A,B.reshape((3,1))))
print(A_System)

[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]


#### 2.2 - Function for Elementary Operations

In [24]:
# exchange row_num of the matrix M with its multiple by row_num_multiple

def MultiplyRow(M, row_num, row_num_multiple):
    M_new = M.copy()
    # M_new = M # if you want to change the original matrix
    M_new[row_num]= M_new[row_num]*row_num_multiple
    return M_new

print("Original matrix:")
print(A_System)
print("\nAfter multiplying row 2 by 2:")
print(MultiplyRow(A_System,1,2))

print(f"\n {A_System}")


Original matrix:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

After multiplying row 2 by 2:
[[  4.  -3.   1. -10.]
 [  4.   2.   6.   0.]
 [ -1.   2.  -5.  17.]]

 [[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]
